<?php
/**
* @file
* A description of what your module does.
*/

function allegro_client() {

}

function allegro_test_connection() {
    $credentials = allegro_credentials_object();
    $username = $credentials->getUsername();
    $pass = $credentials->getPassword();
    $key = $credentials->getWebAPIkey();
    $test_mode = $credentials->isTestMode();
    $country_code = $credentials->getCountryCode();

    if (! ($username && $pass && $key && $country_code)) {
        return false;
    }

    try {
        \Drupal\allegro\Util\AllegroAPI::testConnection($username, $pass, $key, $country_code, $test_mode);
        return true;
    } catch(SoapFault $e) {
        if ($test_mode) {
            drupal_set_message($e->getMessage(), 'error');
        } else {
            \Drupal::logger('allegro')->warning('Allegro connection error: @message', ['@message' => $e->getMessage()]);
        }
    }
    return false;


}

function allegro_credentials_object() {
  return \Drupal\allegro\Util\AllegroCredentials::get();
}