<?php

/**
 * @file
 * Contains allegro_category.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function allegro_category_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the allegro_category module.
    case 'help.page.allegro_category':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Support for Allegro categorization.') . '</p>';
      return $output;

    default:
  }
}
